# FORMAT
format = """
[](color3)\
[ ](bg:color3)\
$username\
[](bg:color1 fg:color3)\
$directory\
[](fg:color1 bg:color2)\
$git_branch\
$git_status\
[](fg:color2 bg:color4)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:color4 bg:color5)\
$docker_context\
[](fg:color5 bg:color6)\
$time\
[ ](fg:color6)\
"""
command_timeout = 5000
#add_newline = false

## COLORS
palette = 'imachina'

[palettes.ctt]
color3 = '#3B4252'
color1 = '#434C5E'
color2 = '#4C566A'
color4 = '#86BBD8'
color5 = '#06969A'
color6 = '#33658A'

[palettes.imachina]
color3 = '#222236'
color1 = '#29293f'
color2 = '#32324d'
color4 = '#837dd7'
color5 = '#6d98e8'
color6 = '#65dedc'

## MODULES
# You can also replace your username with a neat symbol like  to save some space
[username]
disabled = true
show_always = true
style_user = "bg:color3"
style_root = "fg:color5 bold bg:color3"
format = '[$user ]($style)'

[directory]
style = "bg:color1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:color5"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:color2"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color2"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:color4"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:color6"
format = '[ $time]($style)'

# to show container in case of distrobox
[custom.toolbox]
disabled = true
description = "active toolbox"
command = """grep -Po 'name="\\K[^"]+' /run/.containerenv"""
when = "test -f /run/.containerenv"
symbol = " "
format = '[$output$symbol ]($style)'
style = "fg:color5 bold bg:color3"
