#!/bin/sh
# script outputs current screen brightness %

for folders in /sys/class/backlight/*/; do
    backlight="$folders"
done

# if there isn't any backlight then exit
[ -d "$backlight" ] || exit

max_brightness=$(cat "$backlight/max_brightness")
# if max_brightness is empty then do not output anything
[ -z $max_brightness ] && exit

brightness=$(cat "$backlight/brightness")
percent=$(( brightness * 100 / max_brightness ))

# full text
echo "$percent"
# short text
echo ""
