#!/bin/sh
# script outputs current battery % and battery charge status
# REQUIRES: upower

path_to_battery=$(upower -e | grep BAT)

# if no battery found, exit
[ "$path_to_battery" = "" ] && exit

battery_level=$(upower -i "$path_to_battery"  | grep -E "percentage" | sed 's/[^0-9]//g')
state=$(upower -i "$path_to_battery"  | grep -E "state" | sed 's/.*:[[:space:]]*//')

if [ $battery_level -le 15 ]; then
    label=" "
    color="#ff0000"
elif [ $battery_level -le 30 ]; then
    label=" "
    color="#ffae00"
elif [ $battery_level -le 60 ]; then
    label=" "
    color="#fff600"
elif [ $battery_level -le 85 ]; then
    label=" "
    color="#a8ff00"
else
    label=" "
fi

if [ "$state" = "discharging" ]; then
    label="$label"
elif [ "$state" = "charging" ]; then
    label="$label"
# example of "pending-charge state", no colored label, battery not 100% label
else
    label=" "
    color=""
fi

full_text="$battery_level%"
echo "$label $full_text"
echo "$label $full_text"
echo "$color"
