#!/bin/sh
# script outputs current package0 temp in C

# hwmon4-temp1 is cpu pkg temp
file="/sys/class/hwmon/hwmon4/temp1_input"

# if file doesn't exit, then exit
[ -f "$file" ] || exit

temp=$(cat "$file")

# remove 3 trailing zeros
temp="${temp%???}"

# full text
echo "$temp°C"
# short text
echo "$label$temp"

# color
if [ $temp -ge 80 ]; then
    echo "#FF0000"
elif [ $temp -ge 70 ]; then
    echo "#FFFC00"
fi
