#!/bin/sh
# script outputs only when gamemode is enabled, like the gnome
#  extension
# REQUIRES: gamemode

# if gamemode is not installed, exit silently
if ! command -v gamemoded >/dev/null 2>&1; then exit; fi

# if gamemode is disabled, dont output anything
if [ "$(gamemoded -s)" = "gamemode is inactive" ]; then
    exit
# if gamemode is running then output status
else
    echo "Gamemode"
    echo "Gamemode"
    echo "#78dca7"
fi

