#!/bin/sh
# a system power menu
# REQUIRES: i3lock

# set screen-locker command
lock() {
    i3lock --nofork -c 121314 -f -i ~/.config/lockscreen.png
}

# systemd distros use systemctl, else use loginctl
[ "$(cat /proc/1/comm)" = "systemd" ] && ctl=systemctl || ctl=loginctl

case "$1" in
    lock)
        lock &
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock &
        sleep 1
        $ctl suspend
        ;;
    hibernate)
        lock &
        sleep 1
        $ctl hibernate
        ;;
    reboot)
        $ctl reboot
        ;;
    poweroff)
        $ctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|poweroff}"
        exit 2
esac

exit 0
