#!/bin/sh
# a system power menu for both X11 and Wayland
# REQUIRES: i3lock, swaylock

# set screen-locker command
lock() {
    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        swaylock -f -c 121314 -i ~/.config/lockscreen.png -s fit
    else
        i3lock --nofork -c 121314 -f -i ~/.config/lockscreen.png
    fi
}

# systemd distros use systemctl, else use loginctl
[ "$(cat /proc/1/comm)" = "systemd" ] && ctl=systemctl || ctl=loginctl

case "$1" in
    lock)
        lock &
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock &
        sleep 1
        $ctl suspend
        ;;
    hibernate)
        lock &
        sleep 1
        $ctl hibernate
        ;;
    reboot)
        $ctl reboot
        ;;
    poweroff)
        $ctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|poweroff}"
        exit 2
esac

exit 0
