#!/bin/sh
# script to show current power profile
# on click it calls a script to manage active power profile

file="/sys/devices/system/cpu/cpufreq/policy0/energy_performance_preference"

# if cpu does not support energe-performance pref, don't show anything
[ -f "$file" ] || exit

current_profile=$(cat "$file")

case $current_profile in
	power)
	    echo ""
	    echo ""
	    echo "#78DCA7"
	;;
	performance)
	    echo ""
	    echo ""
	    echo "#D95177"
	;;
    *)
	    #   󰗑
        echo "󰚀 "
	    echo "󰚀 "
	    echo "#759EEA"
    ;;
esac

if [ "$button" = "1" ]; then
    "$HOME"/.local/bin/rofi-ppd
fi
