#!/usr/bin/env sh
# script to show current power profile
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

current_profile=$(/usr/bin/powerprofilesctl get)

case $current_profile in
	power-save)
	    echo ""
	    echo ""
	    echo "#78DCA7"
	;;
	balanced)
	#   󰗑
	    echo "󰚀"
	    echo "󰚀"
	    #echo "#759EEA"
	;;
	performance)
	    echo ""
	    echo ""
	    echo "#D95177"
	;;
esac
