#!/usr/bin/env bash

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlp0s20f3}"
fi
#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
# Similarly, if the wifi interface exists but no connection is active, show
# nothing
[[ ! -d /sys/class/net/"${INTERFACE}"/wireless || \
    "$(cat /sys/class/net/"$INTERFACE"/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------
#SSID=$(iw "$INTERFACE" info | awk '/ssid/ {$1=""; print $0}')
SSID=$(LANG=C nmcli d | grep -Ei 'wlp0s20f3.*connected' | grep -vi 'disconnected' | awk '{print $4}')
#------------------------------------------------------------------------
SHORT_SSID="${SSID: -4}"
COLOR="#78DCA7"

echo "$SSID"
echo "$SHORT_SSID"
echo "$COLOR"
