#!/bin/sh
# Script checks for number of available updates, and sends a notification for how many
#  there are and which of them. Also check for update errors and notifys appropriately

case $button in
    1) $TERM -e sh -c "less /tmp/updates"
        exit
    ;;
esac

/bin/xbps-install --dry-run --update --memory-sync 1>/tmp/updates 2>/tmp/error
date >> $HOME/updates_log
updates="$(wc -l < /tmp/updates)"
broken="$(grep broken /tmp/error | wc -l)"

if [ "$broken" -ge 1 ]; then
    echo " ERR!"
elif [ "$updates" -ge 1 ]; then
    echo " $updates"
else
    # if up-to-date system, don't output anything
    exit
fi
