#!/usr/bin/env bash
# outputs current connected wifi SSID and signal %
# output is color graded
# left-click: toggle SSID output
# right-click: opens nmcli to manage connections
# middle-click: toggles wifi state
# REQUIRES: iw to display info, NetworkManager for connection handling

#TERM=i3-sensible-terminal

if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlp0s20f3}"
fi

COLOR_GE80=${COLOR_GE80:-#78DCA7}
COLOR_GE60=${COLOR_GE60:-#FCF39C}
COLOR_GE40=${COLOR_GE40:-#DBC074}
COLOR_LOWR=${COLOR_LOWR:-#D95177}
COLOR_DOWN=${COLOR_DOWN:-#D95177}

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo $COLOR_DOWN
    if [[ "$BLOCK_BUTTON" -eq 2 ]]; then
		nmcli device up	"$INTERFACE"
    elif [[ "$BLOCK_BUTTON" -eq 3 ]]; then
        $TERM -T nmtui -e nmtui
	fi
    exit
fi

#SSID=$(LANG=C nmcli d | grep -Ei 'wifi.*connected' | grep -vi 'disconnected' | awk '{print $4}')
SSID=$(iw "$INTERFACE" info | awk '/ssid / {$1=""; print $0}')
SHORT_SSID="*${SSID: -3}"
QUALITY=$(iw ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')
QUALITYdBm=$(iw ${INTERFACE} link | grep dBm | grep -Eoe '-[0-9]{2} dBm')

# color
if [[ $QUALITY -ge 75 ]]; then
    COLOR=$COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    COLOR=$COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    COLOR=$COLOR_GE40
else
    COLOR=$COLOR_LOWR
fi

toggle_wifi() {
	if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
		nmcli device up	"$INTERFACE"
	else
		nmcli device down "$INTERFACE"
	fi
	}

case "$BLOCK_BUTTON" in
    1)
        echo "$QUALITYdBm$SSID"
        echo "$label$SSID"
        echo "$COLOR"
        exit
        ;;
    2) toggle_wifi ;;
    3) $TERM -T nmtui -e nmtui ;;
esac

# full text
echo "$QUALITY"
# short text
echo "$label$QUALITY"
# color
echo "$COLOR"
