#!/usr/bin/env bash

if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlp0s20f3}"
fi

COLOR_GE80=${COLOR_GE80:-#78DCA7}
COLOR_GE60=${COLOR_GE60:-#FCF39C}
COLOR_GE40=${COLOR_GE40:-#DBC074}
COLOR_LOWR=${COLOR_LOWR:-#D95177}
COLOR_DOWN=${COLOR_DOWN:-#D95177}

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo $COLOR_DOWN
    exit
fi

#SSID=$(iw "$INTERFACE" info | awk '/ssid/ {$1=""; print $0}')
SSID=$(LANG=C nmcli d | grep -Ei 'wifi.*connected' | grep -vi 'disconnected' | awk '{print $4}')
SHORT_SSID="*${SSID: -3}"
QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

# color
if [[ $QUALITY -ge 80 ]]; then
    COLOR=$COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    COLOR=$COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    COLOR=$COLOR_GE40
else
    COLOR=$COLOR_LOWR
fi

echo "$QUALITY% $SSID"
echo "$QUALITY% $SHORT_SSID"
echo $COLOR
